apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-html
  labels:
    app: example-html
spec:
  selector:
    matchLabels:
      app: example-html
  template:
    metadata:
      labels:
        app: example-html
    spec:
      initContainers:
      - name: pending
        image: busybox
        command: ["sleep", "10"]
      containers:
      - name: example-html
        image: example-html-image
        ports:
        - containerPort: 8000
