apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example-html
  labels:
    app: example-html
spec:
  template:
    metadata:
      labels:
        app: example-html
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: example-html
        image: example-html-image
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /index.html
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3
